# Copyright 2024 Canonical Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: lldpd charm tests
on:
  workflow_call:
  pull_request:
  # FIXME: remove before merging
  push:

jobs:
  inclusive-naming-check:
    name: Inclusive naming check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: woke
        uses: get-woke/woke-action@v0
        with:
          # Cause the check to fail on any broke rules
          fail-on-error: true

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.6
        uses: actions/setup-python@v5
        with:
          python-version: 3.6
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run linters
        run: tox -e lint

  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.6
        uses: actions/setup-python@v5
        with:
          python-version: 3.6
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run static analysis
        run: tox -e static-charm

  unit-test:
    name: Unit tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.6
        uses: actions/setup-python@v5
        with:
          python-version: 3.6
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run tests
        run: tox -e unit

  integration-test:
    strategy:
      fail-fast: true
      matrix:
        bases:
          - bionic`
    name: Integration tests (LXD) | ${{ matrix.bases }}
    runs-on: ubuntu-latest
    needs:
      - inclusive-naming-check
      - lint
      - unit-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd
          juju-channel: 2.9/stable
      - name: Run tests
        run: tox run -e integration -- --charm-base=${{ matrix.bases }}
